### ISSUE TITLE
Using non-unique cycle finding as invariant

### ISSUE THREAD

**Issue by johnmay** [JanCBrammer/TUCAN#52]
I had not heard of the CycleCut method before and it appears to be a non-unique cycle basis. Finding cycles using a breath-first search you essentially end up with multiple shortest paths and you get one dependant on the input order. Here are some investigations and explanation - at the very least I think it needed a clearer explanation in the manuscript.

A simple to follow case is the following:

```
C1(CC2)CCC(CCC3CCC2CC3)CC1
```
![image](https://user-images.githubusercontent.com/983232/159923335-28fe9fa7-236c-4f49-9ca3-4eb65dc6fd2c.png)

I get 3 rings here, 2x size 6 and 1x size 12. The size 12 one will depend on the order the BFS traversed the nodes/edges.

![image](https://user-images.githubusercontent.com/983232/159926902-155305ed-bb8c-4abd-b0e3-5a82e7811397.png)

```
>>> _find_atomic_cycles(graph_from_smiles("C1(CC2)CCC(CCC3CCC2CC3)CC1"))
[{0, 3, 4, 5, 14, 15}, {8, 9, 10, 11, 12, 13}, {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}]
```

```
>>> _cycle_memberships(m)
{0: {0, 1, 3}, 1: {0, 3}, 2: {0, 3}, 3: {0, 1, 3}, 4: {0, 1, 3}, 5: {0, 1, 3}, 6: {0, 3}, 7: {0, 3}, 8: {0, 2, 3}, 9: {0, 2, 3}, 10: {0, 2, 3}, 11: {0, 2, 3}, 12: {0, 2}, 13: {0, 2}, 14: {0, 1}, 15: {0, 1}}
```
```
0,3,4,5,8,9,10,11 belong to 2 cycles
1,2,6,7,12,13,13,15 belong to 1 cycle
```

Using the print_molecule to get the graph invariants and presuming the indexes match the SMILES I can use CXSMILES to display as follows:

``` 
C1(CC2)CCC(CCC3CCC2CC3)CC1 |$_AV:3,1;3;3;3,1;3,1;3,1;3;3;3,2;3,2;3,2;3,2;2;2;1;1$|
```

![](https://www.simolecule.com/cdkdepict/depict/bow/svg?smi=C1(CC2)CCC(CCC3CCC2CC3)CC1%20%7C%24_AV%3A3%2C1%3B3%3B3%3B3%2C1%3B3%2C1%3B3%2C1%3B3%3B3%3B3%2C2%3B3%2C2%3B3%2C2%3B3%2C2%3B2%3B2%3B1%3B1%24%7C&w=-1&h=-1&abbr=on&hdisp=bridgehead&showtitle=false&zoom=1.25&annotate=atomvalue&r=0)

To me this looks the invariant is splitting atoms which are symmetric - i.e. it's not invariant? Beyond the non-uniqueness using the cycle id like this means you also introduce an artificial split.

Useful reading on ring/cycle algorithms:
https://jcheminf.biomedcentral.com/articles/10.1186/1758-2946-6-3
https://www.combinatorics.org/ojs/index.php/eljc/article/view/v4i1r9/pdf

**Comment by johnmay** [comment]
One thing that is confusing is I would expect something simple like:

```
C1CCCCC1CCC(C)C1CCCCC1
C1CCCCC1C(C)CCC1CCCCC1
```

generate different ID's - since the invariant code use the cycleid (which depends on the order of the cycle in the molecule) but this is not the case:

```
>>> serialize_molecule(graph_from_smiles("C1CCCCC1C(C)CCC1CCCCC1"))
'C16/1-15/2-3/2-14/3-4/4-5/5-6/6-14/7-8/7-15/8-16/9-10/9-16/10-11/11-12/12-13/13-16/14-15'
>>> serialize_molecule(graph_from_smiles("C1CCCCC1CCC(C)C1CCCCC1"))
'C16/1-15/2-3/2-14/3-4/4-5/5-6/6-14/7-8/7-14/8-15/9-10/9-16/10-11/11-12/12-13/13-16/15-16'
```

I suspected that the encoding "gets lucky" with a starting point, we can force it to start somewhere else:

```
C1CC([Li])CCC1C(C)CCC1CCC([Li])CC1 NDINSTUPYQAZRK-UHFFFAOYSA-N
C1CC([Li])CCC1CCC(C)C1CCC([Li])CC1 NDINSTUPYQAZRK-UHFFFAOYSA-N
```

```
>>> serialize_molecule(graph_from_smiles("C1CC([Li])CCC1C(C)CCC1CCC([Li])CC1"))
'C16Li2/1-14/2-15/3-17/4-5/4-16/5-14/6-7/6-14/7-16/8-9/8-17/9-18/10-11/10-18/11-15/12-13/12-15/13-18/16-17'
>>> serialize_molecule(graph_from_smiles("C1CC([Li])CCC1CCC(C)C1CCC([Li])CC1"))
'C16Li2/1-14/2-15/3-17/4-5/4-16/5-14/6-7/6-14/7-16/8-9/8-16/9-17/10-11/10-18/11-15/12-13/12-15/13-18/17-18'
```

**Comment by johnmay** [comment]
Sorry my mistake - that first one is different! "/14-15" and "/15-16" at the end. Was hard to spot with all the numbers.

**Comment by JanCBrammer** [comment]
You're right, it seems like my implementation of CycleCut does return cycles _with_ chords (see cycle `3`), will investigate...
```
m = graph_from_smiles("C1(CC2)CCC(CCC3CCC2CC3)CC1")

cycle_memberships = nx.get_node_attributes(m, "cycle_membership")
cycle_memberships_str = dict([k, str(v - {0})] for k, v in cycle_memberships.items())

draw_molecules([m], [""], labels=cycle_memberships_str)
```

![output](https://user-images.githubusercontent.com/30125107/159957378-d4a5c0af-4df8-41e2-95a2-edd95643a82c.png)

Will come back to this next week, thanks for the input so far!

**Comment by johnmay** [comment]
Just to be clear there are two separate (but related issues).

1. The cycle id depends on the input order and as such identical molecules ordered differently get different identifiers. There is no mixup with "chordless" cycles in this example.
```
C1CCCCC1CCC(C)C1CCCCC1 -> C16/1-15/2-3/2-14/3-4/4-5/5-6/6-14/7-8/7-15/8-16/9-10/9-16/10-11/11-12/12-13/13-16/14-15
C1CCCCC1C(C)CCC1CCCCC1 -> C16/1-15/2-3/2-14/3-4/4-5/5-6/6-14/7-8/7-14/8-15/9-10/9-16/10-11/11-12/12-13/13-16/15-16
```

2. The cycle basis is non-unique paths generate by the cycles depends on the order generated. As you say "chordless" but I'm not sure that concept extends beyond a single edge and a non-unique way.

**Comment by JanCBrammer** [comment]
@johnmay, I think I got to the bottom of the issue.

The cycle ID is indeed unsuitable as an invariant for the two reasons you mention above.

The tests did not catch these problems since the tests were wrong. Turns out, your suspicion of the passing test on the `rigid graph benchmark` is quite justified ;) I felt uneasy about it (the passing tests) as well...

Here's the problem:
In the [shuffle test](https://github.com/JanCBrammer/TUCAN/blob/d3e8a2b8c08a508f8a292fb570df3504581758e5/tests/test_canonicalization.py#L23), the node labels are permuted correctly. However, the cycle IDs get computed and assigned during the [instantiation of the original graph](https://github.com/JanCBrammer/TUCAN/blob/d3e8a2b8c08a508f8a292fb570df3504581758e5/tucan/io.py#L57) (i.e., the graph whose nodes are shuffled). That is, during the shuffle test, only the node labels were permuted while the cycle IDs associated with the nodes stayed the same. The cycle IDs stayed the same since the graph wasn't reinstantiated after shuffling (this is fixed now: d3e8a2b8c08a508f8a292fb570df3504581758e5). Therefore, the canonicalization always used the same cycle IDs irrespective of the shuffling.

Back to the drawing board I guess. I'll replace the cycle invariant with the "degree vector" you're suggesting above.

Thanks again for digging into this, and for the (counter-)examples above, they led me to the problem. I needed a second pair of eyes on this!

**Comment by JanCBrammer** [comment]
Another interesing alternative invariant: https://doi.org/10.1186/s13321-020-00453-4.

**Comment by JanCBrammer** [comment]
Closing with 77f67dcaf45a92f856a285dc386ffbb1cf321c41.

**Comment by rapodaca** [comment]
Which approach does the closing commit take? Degree vector, the one proposed by Krotko, or something else?

**Comment by JanCBrammer** [comment]
@rapodaca, none at the moment. I'm planning on implementing the two invariants Krotko proposes (he calls them "ring invariant" and "distance invariant"). Will open an issue to make it clear that this is work in progress.
